'use strict';


angular.module('app', [
    'ngAnimate',
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'ngTouch',
    'ngStorage',
    'ui.router',
    'ui.bootstrap',
    'ui.utils',
    'ui.load',
    'ui.jq',
    'ui.grid',
    'ui.grid.pagination',
    'ui.grid.selection',
    'ui.grid.autoResize',
    "ui.grid.resizeColumns",
    'ui.grid.moveColumns',
    'ui.grid.exporter',
    'oc.lazyLoad',
    'pascalprecht.translate',

    'w5c.validator',
    'angular-confirm',

    'account.alarms',
    'account.app_components',
    'account.app_orders',
    'account.app_recommends',
    'account.app_version_audits',
    'account.app_versions',
    'account.apps',
    'account.articles',
    'account.banners',
    'account.contract_audits',
    'account.contracts',
    'account.files',
    'account.instances',
    'account.managers',
    'account.notices',
    'account.pay_types',
    'account.recharge_logs',
    'account.recharge_orders',
    'account.resources',
    'account.settings',
    'account.sp_application_audits',
    'account.sp_applications',
    'account.user_logs',
    'account.users'
]);